# Generated by Django 3.1.7 on 2021-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='refreshercourse',
            options={'verbose_name': 'Курсы повышения квалификации', 'verbose_name_plural': 'Курсы повышения квалификации'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография врача'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=50, verbose_name='Образование'),
        ),
    ]
