# Generated by Django 3.1.7 on 2021-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пациента')),
                ('user_surname', models.CharField(max_length=50, verbose_name='Отчество пациента')),
                ('user_last_name', models.CharField(max_length=50, verbose_name='Фамилия пациента')),
                ('doctor_name', models.CharField(max_length=50, verbose_name='Имя врача')),
                ('doctor_surname', models.CharField(max_length=50, verbose_name='Отчество врача')),
                ('doctor_last_name', models.CharField(max_length=50, verbose_name='Фамилия врача')),
                ('datetime_record', models.DateTimeField(verbose_name='Дата и время приема')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.BooleanField(default=1, verbose_name='Четверг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.BooleanField(verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.BooleanField(verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=models.BooleanField(verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.BooleanField(verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.BooleanField(verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.BooleanField(verbose_name='Среда'),
        ),
    ]
