# Generated by Django 3.1.7 on 2021-04-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210404_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='doctors.doctor'),
        ),
    ]
